# Generated by Django 4.2.6 on 2023-10-27 03:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_alter_comment_options_newscomment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newscomment",
            old_name="article",
            new_name="news",
        ),
    ]
