services:
  django:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./conf/Dockerfile
    command: /app/conf/run.sh start
    env_file:
      - ./caves.app.env
    ports:
      - "5600:8000"
    networks:
      - cavesapp

networks:
  cavesapp:
    external: true
