services:
  django:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./conf/Dockerfile
    command: /app/conf/run.sh start
    env_file:
      - ./caves.app.env
    ports:
      - "3200:8000"
    networks:
      - cavesapp
    labels:
      cupdate.config.ignore: "true"
    logging:
      driver: loki
      options:
        loki-url: "https://loki.p.hac.sh/loki/api/v1/push"

networks:
  cavesapp:
    external: true
