name: cavesapp-services

services:
  caves-postgres:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./conf/db/Dockerfile
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    ports:
      - "5601:5432"
    env_file:
      - ./caves.app.env
    networks:
      - cavesapp

  caves-redis:
    restart: unless-stopped
    image: redis:8.0
    volumes:
      - ./data/redis/:/data
    env_file:
      - ./caves.app.env
    ports:
      - "5602:6379"
    networks:
      - cavesapp

  caves-imgproxy:
    restart: unless-stopped
    image: ghcr.io/imgproxy/imgproxy:v3.29
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "imgproxy", "health"]
    env_file:
      - ./caves.app.env
    ports:
      - "5603:9000"
    networks:
      - cavesapp

networks:
  cavesapp:
    external: true
