name: cavesapp-services

services:
  caves-postgres:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./conf/db/Dockerfile
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    ports:
      - "3201:5432"
    env_file:
      - ./caves.app.env
    networks:
      - cavesapp
    labels:
      cupdate.config.ignore: "true"
    logging:
      driver: loki
      options:
        loki-url: "https://loki.p.hac.sh/loki/api/v1/push"
  
  caves-redis:
    restart: unless-stopped
    image: redis:8.0
    volumes:
      - ./data/redis/:/data
    env_file:
      - ./caves.app.env
    ports:
      - "3202:6379"
    networks:
      - cavesapp
    logging:
      driver: loki
      options:
        loki-url: "https://loki.p.hac.sh/loki/api/v1/push"

  caves-imgproxy:
    restart: unless-stopped
    image: ghcr.io/imgproxy/imgproxy:v3.29
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "imgproxy", "health"]
    env_file:
      - ./caves.app.env
    ports:
      - "3203:8080"
    networks:
      - cavesapp
    logging:
      driver: loki
      options:
        loki-url: "https://loki.p.hac.sh/loki/api/v1/push"

networks:
  cavesapp:
    external: true
