name: cavesapp-services

services:
  postgres:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./conf/db/Dockerfile
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - cavesapp

  redis:
    restart: unless-stopped
    image: redis:7.4
    volumes:
      - ./data/redis/:/data
    ports:
      - "6379:6379"
    networks:
      - cavesapp

  imgproxy:
    restart: unless-stopped
    image: ghcr.io/imgproxy/imgproxy:v3.27
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "imgproxy", "health"]
    env_file:
      - ./conf/dev.env
    ports:
      - "9000:9000"
    networks:
      - cavesapp

networks:
  cavesapp:
    driver: bridge
