version: '3.8'

services:
  db-dev:
    image: postgres:15.0-alpine
    build:
      context: .
      dockerfile: ./etc/dev/Dockerfile.dev.db
    volumes:
      - ./docker-dev-data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web-dev:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/opt/dev/app/
    ports:
      - "8000:8000"
    env_file:
      - ./etc/dev/dev.env
    depends_on:
      - db-dev
