version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: config/docker/Dockerfile.dev.db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:7.2.1
    volumes:
      - ./data/development/redis:/data
    expose:
      - 6379

  imgproxy:
    image: darthsim/imgproxy:latest
    security_opt:
    - no-new-privileges:true
    healthcheck:
      test: ["CMD", "imgproxy", "health"]
    env_file:
      - ./config/docker/development.env
    ports:
      - "9000:9000"

  web:
    command: python manage.py runserver 0.0.0.0:8000 --insecure
    build:
      context: .
      dockerfile: config/docker/Dockerfile.dev.web
    volumes:
      - ./app/:/opt/dev/app/
      - ./data/development/media:/opt/dev/media/
      - ./data/development/logs:/opt/dev/logs/
      - ./config/django/:/opt/dev/config/django/
    ports:
      - "8000:8000"
    env_file:
      - ./config/docker/development.env
    depends_on:
      - postgres
      - redis
      - imgproxy
