version: '3.8'

services:
  db-prod:
    image: postgres:15.0-alpine
    restart: always
    volumes:
      - caves-prod-db:/var/lib/postgresql/data
    env_file:
      - ./etc/prod/postgres.env
  pgbackups-prod:
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres
    volumes:
      - ./prod-data/backups/db:/backups
    env_file:
      - ./etc/prod/postgres-backup.env
    depends_on:
      - db-prod
  web-prod:
    restart: always
    build:
      context: .
      dockerfile: ./etc/prod/Dockerfile.prod
    command: gunicorn cavinglog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - caves-prod-static:/opt/cavesapp/staticfiles
    expose:
      - 8000
    env_file:
      - ./etc/prod/prod.env
    depends_on:
      - db-prod
  nginx-prod:
    restart: always
    build:
      context: .
      dockerfile: ./etc/prod/Dockerfile.nginx
    volumes:
      - caves-prod-static:/opt/cavesapp/staticfiles
    ports:
      - 8080:80
    depends_on:
      - web-prod

volumes:
  caves-prod-db:
  caves-prod-static:
