version: '3.8'

services:
  db:
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - ./data/production/db:/var/lib/postgresql/data
    env_file:
      - ./config/docker/production/postgres.env

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres
    volumes:
      - ./data/production/backups/db:/backups
    env_file:
      - ./config/docker/production/postgres-backup.env
    depends_on:
      - db

  web:
    restart: always
    user: 1001:1001
    build:
      context: .
      dockerfile: ./config/docker/production/Dockerfile.prod.web
    command: gunicorn config.django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./data/production/staticfiles:/opt/caves/staticfiles
      - ./data/production/media:/opt/caves/media/
      - ./config/django:/opt/caves/config/django
      - ./app:/opt/caves/app
    ports:
      - 8000:8000
    env_file:
      - ./config/docker/production/production.env
    depends_on:
      - db
