version: "3.8"

services:
  imgproxy:
    restart: always
    image: darthsim/imgproxy:latest
    security_opt:
    - no-new-privileges:true
    healthcheck:
      test: ["CMD", "imgproxy", "health"]
    env_file:
      - ./config/docker/production/production.env
    ports:
      - ${IMGPROXY_BIND_PORT:-9000}:${IMGPROXY_BIND_PORT:-9000}

  web:
    restart: always
    user: ${UID}:${GID}
    build:
      context: .
      dockerfile: ./config/docker/production/Dockerfile.prod.web
    command: gunicorn config.django.wsgi:application --bind ${CAVES_BIND_ADDR:-0.0.0.0}:${CAVES_BIND_PORT:-8000} --log-file /opt/caves/logs/gunicorn/gunicorn.log --workers 17
    volumes:
      - ./data/production/staticfiles:/opt/caves/staticfiles
      - ./data/production/logs:/opt/caves/logs
      - ./config/django:/opt/caves/config/django
      - ./app:/opt/caves/app
    ports:
      - ${CAVES_BIND_PORT:-8000}:${CAVES_BIND_PORT:-8000}
    env_file:
      - ./config/docker/production/production.env
