version: '3.8'

services:
  db:
    image: postgres:15.0-alpine
    restart: always
    volumes:
      - ./prod-data/db:/var/lib/postgresql/data
    env_file:
      - ./etc/prod/postgres.env

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres
    volumes:
      - ./prod-data/backups/db:/backups
    env_file:
      - ./etc/prod/postgres-backup.env
    depends_on:
      - db

  web:
    restart: always
    user: 1001:1001
    build:
      context: .
      dockerfile: ./etc/prod/Dockerfile.prod
    command: gunicorn cavinglog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./prod-data/staticfiles:/opt/caves/staticfiles
      - ./app:/opt/caves/app
    ports:
      - 8000:8000
    env_file:
      - ./etc/prod/prod.env
    depends_on:
      - db
