version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: config/docker/db/Dockerfile
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:latest
    volumes:
      - redis:/data
    expose:
      - 6379

  imgproxy:
    image: darthsim/imgproxy:latest
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "imgproxy", "health"]
    env_file:
      - config/env/dev.env
    ports:
      - "9000:9000"

  web:
    command: /app/run.sh devserver
    build: .
    volumes:
      - ./app/:/app/src
      - ./config/django/:/app/config/django/
      - mediafiles:/app/mediafiles/
      - staticfiles:/app/staticfiles/
      - logs:/app/logs/
    ports:
      - "8000:8000"
    env_file:
      - ./config/env/dev.env
    depends_on:
      - db
      - redis
      - imgproxy

volumes:
  db:
  redis:
  mediafiles:
  staticfiles:
  logs:
