version: '3.8'

services:
  db-dev:
    build:
      context: .
      dockerfile: ./config/docker/development/Dockerfile.dev.db
    volumes:
      - ./data/development/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis-dev:
    image: redis:7.0.11-alpine
    volumes:
      - ./data/development/redis:/data
    expose:
      - 6379

  imgproxy-dev:
    image: darthsim/imgproxy:latest
    security_opt:
    - no-new-privileges:true
    healthcheck:
      test: ["CMD", "imgproxy", "health"]
    env_file:
      - ./config/docker/development/development.env
    ports:
      - 9000:9000

  web-dev:
    command: python manage.py runserver 0.0.0.0:8000 --insecure
    build:
      context: .
      dockerfile: ./config/docker/development/Dockerfile.dev.web
    volumes:
      - ./app/:/opt/dev/app/
      - ./data/development/media:/opt/dev/media/
      - ./config/django/:/opt/dev/config/django/
    ports:
      - "8000:8000"
    env_file:
      - ./config/docker/development/development.env
    depends_on:
      - db-dev
      - redis-dev
