# Generated by Django 4.1.7 on 2023-02-26 15:14

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cavinguser",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(
                choices_display="WITH_GMT_OFFSET", default="Europe/London"
            ),
        ),
        migrations.AddField(
            model_name="cavinguser",
            name="units",
            field=models.CharField(default="Metric", max_length=10),
        ),
    ]
