# Generated by Django 4.1.7 on 2023-03-24 23:32

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cavinguser",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(
                choices_display="WITH_GMT_OFFSET",
                default="Europe/London",
                help_text="Timezone to enter and display dates and times in.",
            ),
        ),
        migrations.AlterField(
            model_name="cavinguser",
            name="units",
            field=models.CharField(
                choices=[("Metric", "Metric"), ("Imperial", "Imperial")],
                default="Metric",
                help_text="Preferred units of distance.",
                max_length=10,
                verbose_name="Distance units",
            ),
        ),
    ]
