# Generated by Django 4.1.7 on 2023-03-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cavinguser",
            name="privacy",
            field=models.CharField(
                choices=[
                    ("Default", "Default"),
                    ("Public", "Public"),
                    ("Private", "Private"),
                ],
                default="Default",
                max_length=10,
                verbose_name="Privacy settings",
            ),
        ),
    ]
