# Generated by Django 4.1.7 on 2023-03-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_cavinguser_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="cavinguser",
            name="club",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
