# Generated by Django 4.1.7 on 2023-03-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_cavinguser_timezone_alter_cavinguser_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="cavinguser",
            name="profile_page_title",
            field=models.CharField(
                blank=True,
                help_text="A title to display on your profile page. Default is your name.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="cavinguser",
            name="show_statistics",
            field=models.BooleanField(
                default=True,
                help_text="Whether to show statistics on your profile.",
                verbose_name="Show statistics",
            ),
        ),
    ]
