# Generated by Django 4.1.7 on 2023-03-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_cavinguser_profile_page_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cavinguser",
            name="profile_page_title",
            field=models.CharField(
                blank=True,
                help_text="A title to display on your profile page. If left blank it will use your full name.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="cavinguser",
            name="show_statistics",
            field=models.BooleanField(
                default=True,
                help_text="Should the statistics table be displayed on your public profile?",
                verbose_name="Show statistics",
            ),
        ),
    ]
