# Generated by Django 4.2 on 2023-04-28 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_copy_profile_and_settings_data_to_user_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="user",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
        migrations.DeleteModel(
            name="UserSettings",
        ),
    ]
