# Generated by Django 4.1.7 on 2023-03-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_cavinguser_club"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cavinguser",
            name="email_verified",
        ),
        migrations.AlterField(
            model_name="cavinguser",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="enabled user?"),
        ),
    ]
