# Generated by Django 4.1.7 on 2023-03-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_cavinguser_profile_page_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cavinguser",
            name="private_notes",
            field=models.BooleanField(
                default=True,
                help_text="Check this box to prevent your trip notes being displayed on your public profile (if enabled).",
                verbose_name="Keep notes private",
            ),
        ),
        migrations.AlterField(
            model_name="cavinguser",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Information about you that will be displayed on your public profile.",
                verbose_name="biography",
            ),
        ),
        migrations.AlterField(
            model_name="cavinguser",
            name="profile_page_title",
            field=models.CharField(
                blank=True,
                help_text="A title to display on your profile page (if enabled). If left blank it will use your full name.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="cavinguser",
            name="show_statistics",
            field=models.BooleanField(
                default=True,
                help_text="Check this box to show a statistics table on your public profile (if enabled).",
                verbose_name="Show statistics",
            ),
        ),
    ]
