# Generated by Django 4.2 on 2023-04-29 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_usersettings_user_delete_userprofile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cavinguser",
            name="name",
            field=models.CharField(
                default="Caver",
                help_text="Your name as you would like it to appear on your public profile.",
                max_length=35,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
    ]
