# Generated by Django 4.1.7 on 2023-03-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_cavinguser_private_notes_alter_cavinguser_bio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cavinguser",
            name="last_name",
        ),
        migrations.RenameField(
            model_name="cavinguser",
            old_name="first_name",
            new_name="name",
        ),
    ]
