# Generated by Django 4.2 on 2023-04-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_cavinguser_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cavinguser",
            name="clubs",
            field=models.CharField(
                blank=True,
                help_text="A list of caving clubs or organisations that you are a member of.",
                max_length=100,
            ),
        ),
    ]
