# Generated by Django 4.1.7 on 2023-03-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_cavinguser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cavinguser",
            name="name",
            field=models.CharField(
                help_text="Your name as you would like it to appear on your public profile.",
                max_length=30,
            ),
        ),
    ]
