# Generated by Django 4.1.7 on 2023-03-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_cavinguser_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cavinguser",
            name="privacy",
            field=models.CharField(
                choices=[
                    ("Public", "Anyone"),
                    ("Friends", "Only my friends"),
                    ("Private", "Only me"),
                ],
                default="Private",
                help_text="Who can view your profile?",
                max_length=10,
                verbose_name="Profile privacy",
            ),
        ),
    ]
