# Generated by Django 4.1.7 on 2023-04-15 22:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_cavinguser_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="cavinguser",
            name="friends",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
