# Generated by Django 4.2.1 on 2023-06-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_cavinguser_feed_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="cavinguser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="A profile picture to display on your public profile.",
                upload_to="avatars/",
            ),
        ),
    ]
