# Generated by Django 4.1.7 on 2023-04-18 13:06

import django.db.models.deletion
import django_countries.fields
import timezone_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_cavinguser_friends"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "units",
                    models.CharField(
                        choices=[("Metric", "Metric"), ("Imperial", "Imperial")],
                        default="Metric",
                        help_text="Preferred units of distance.",
                        max_length=10,
                        verbose_name="Distance units",
                    ),
                ),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("Public", "Anyone"),
                            ("Friends", "Only my friends"),
                            ("Private", "Only me"),
                        ],
                        default="Private",
                        help_text="Who can view your profile?",
                        max_length=10,
                        verbose_name="Profile privacy",
                    ),
                ),
                (
                    "timezone",
                    timezone_field.fields.TimeZoneField(
                        choices_display="WITH_GMT_OFFSET",
                        default="Europe/London",
                        help_text="Timezone to enter and display dates and times in.",
                    ),
                ),
                (
                    "profile_page_title",
                    models.CharField(
                        blank=True,
                        help_text="A title to display on your profile page (if enabled). If left blank it will use your full name.",
                        max_length=50,
                    ),
                ),
                (
                    "show_statistics",
                    models.BooleanField(
                        default=True,
                        help_text="Check this box to show a statistics table on your public profile (if enabled).",
                        verbose_name="Show statistics",
                    ),
                ),
                (
                    "private_notes",
                    models.BooleanField(
                        default=True,
                        help_text="Check this box to prevent your trip notes being displayed on your public profile (if enabled).",
                        verbose_name="Keep notes private",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Caver",
                        help_text="Your name as you would like it to appear on your public profile.",
                        max_length=30,
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="A profile picture to display on your public profile.",
                        upload_to="avatars/",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=50)),
                (
                    "country",
                    django_countries.fields.CountryField(blank=True, max_length=2),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Information about you that will be displayed on your public profile.",
                        verbose_name="biography",
                    ),
                ),
                (
                    "clubs",
                    models.CharField(
                        blank=True,
                        help_text="A list of caving clubs or organisations that you are a member of.",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
