# Generated by Django 4.2.1 on 2023-06-01 15:01

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_cavinguser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cavinguser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="A profile picture to display on your public profile.",
                upload_to=users.models.avatar_upload_path,
            ),
        ),
    ]
