# Generated by Django 4.2.1 on 2023-06-02 00:05

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_cavinguser_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="cavinguser",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="A unique identifier for this user.",
                null=True,
            ),
        ),
    ]
