# Generated by Django 4.1.7 on 2023-04-18 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_copy_profile_and_settings_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usersettings",
            options={"verbose_name_plural": "user settings"},
        ),
        migrations.RemoveField(
            model_name="cavinguser",
            name="name",
        ),
    ]
