# Generated by Django 4.1.7 on 2023-04-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_usersettings_options_remove_cavinguser_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cavinguser",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="cavinguser",
            name="clubs",
        ),
        migrations.RemoveField(
            model_name="cavinguser",
            name="country",
        ),
        migrations.RemoveField(
            model_name="cavinguser",
            name="friends",
        ),
        migrations.RemoveField(
            model_name="cavinguser",
            name="location",
        ),
        migrations.RemoveField(
            model_name="cavinguser",
            name="privacy",
        ),
        migrations.RemoveField(
            model_name="cavinguser",
            name="private_notes",
        ),
        migrations.RemoveField(
            model_name="cavinguser",
            name="profile_page_title",
        ),
        migrations.RemoveField(
            model_name="cavinguser",
            name="show_statistics",
        ),
        migrations.RemoveField(
            model_name="cavinguser",
            name="timezone",
        ),
        migrations.RemoveField(
            model_name="cavinguser",
            name="units",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="friends",
            field=models.ManyToManyField(blank=True, to="users.userprofile"),
        ),
    ]
