# Generated by Django 4.2.1 on 2023-06-02 00:11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_cavinguser_set_uuid_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cavinguser",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="A unique identifier for this user.",
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
