# Generated by Django 4.2.1 on 2023-06-02 12:29

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_alter_cavinguser_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cavinguser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="A profile picture to display on your public profile.",
                upload_to=users.models.avatar_upload_path,
                verbose_name="profile picture",
            ),
        ),
    ]
