# Generated by Django 4.2.1 on 2023-06-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_alter_cavinguser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cavinguser",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Information about you that will be displayed on your public profile. Some <a href='https://www.markdownguide.org/basic-syntax/'>Markdown</a> is supported.",
                verbose_name="biography",
            ),
        ),
    ]
