# Generated by Django 4.1.7 on 2023-04-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_alter_userprofile_friends_alter_userprofile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="show_statistics",
            field=models.BooleanField(
                default=True,
                help_text="Check this box to show a statistics table on your public profile (if enabled).",
                verbose_name="Show statistics",
            ),
        ),
    ]
