# Generated by Django 4.1.7 on 2023-04-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_notification_friendrequest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="name",
            field=models.CharField(
                default="Caver",
                help_text="Your name as you would like it to appear on your public profile.",
                max_length=25,
            ),
        ),
    ]
