# Generated by Django 4.2 on 2023-04-23 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_alter_userprofile_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="name",
            field=models.CharField(
                default="Caver",
                help_text="Your name as you would like it to appear on your public profile.",
                max_length=25,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
    ]
