# Generated by Django 4.2.2 on 2023-06-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_cavinguser_show_cavers_on_trip_list_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cavinguser",
            name="private_notes",
            field=models.BooleanField(
                default=True,
                help_text="Enable this option to prevent your trip notes being displayed to other users when they view your trips.",
                verbose_name="Keep notes private",
            ),
        ),
        migrations.AlterField(
            model_name="cavinguser",
            name="show_cavers_on_trip_list",
            field=models.BooleanField(
                default=True,
                help_text="Enabling this option will display a list of cavers beneath each trip on your profile trip list.",
                verbose_name="Show cavers on trip list",
            ),
        ),
    ]
