# Generated by Django 4.2.2 on 2023-06-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_alter_cavinguser_private_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cavinguser",
            name="custom_field_1_label",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name="cavinguser",
            name="custom_field_2_label",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name="cavinguser",
            name="custom_field_3_label",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name="cavinguser",
            name="custom_field_4_label",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name="cavinguser",
            name="custom_field_5_label",
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
