# Generated by Django 4.2 on 2023-04-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_alter_userprofile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="allow_comments",
            field=models.BooleanField(
                default=True,
                help_text="If enabled, other users will be able to comment on your trips and trip reports. Disabling this setting will not delete any existing comments, but will hide them until it is re-enabled.",
                verbose_name="Allow comments on your trips",
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="allow_friend_email",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, other users will be able to add you as a friend by entering your email address. This will not affect your ability to add other users as friends.",
                verbose_name="Allow friend requests by email",
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="allow_friend_username",
            field=models.BooleanField(
                default=True,
                help_text="If enabled, other users will be able to add you as a friend by entering your username. This will not affect your ability to add other users as friends.",
                verbose_name="Allow friend requests by username",
            ),
        ),
    ]
