# Generated by Django 4.2.2 on 2023-06-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_cavinguser_custom_field_1_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cavinguser",
            name="custom_field_1_label",
            field=models.CharField(blank=True, max_length=25, verbose_name="Custom field 1"),
        ),
        migrations.AlterField(
            model_name="cavinguser",
            name="custom_field_2_label",
            field=models.CharField(blank=True, max_length=25, verbose_name="Custom field 2"),
        ),
        migrations.AlterField(
            model_name="cavinguser",
            name="custom_field_3_label",
            field=models.CharField(blank=True, max_length=25, verbose_name="Custom field 3"),
        ),
        migrations.AlterField(
            model_name="cavinguser",
            name="custom_field_4_label",
            field=models.CharField(blank=True, max_length=25, verbose_name="Custom field 4"),
        ),
        migrations.AlterField(
            model_name="cavinguser",
            name="custom_field_5_label",
            field=models.CharField(blank=True, max_length=25, verbose_name="Custom field 5"),
        ),
    ]
