# Generated by Django 4.2.2 on 2023-06-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_alter_cavinguser_custom_field_1_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cavinguser",
            name="email_friend_requests",
            field=models.BooleanField(
                default=True,
                help_text="Send an email when another user adds you as a friend.",
                verbose_name="Friend request emails",
            ),
        ),
    ]
