# Generated by Django 4.2 on 2023-04-24 08:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_copy_profile_name_to_user_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="name",
        ),
    ]
