# Generated by Django 4.2.3 on 2023-07-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0028_alter_cavinguser_public_statistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="cavinguser",
            name="email_comments",
            field=models.BooleanField(
                default=True,
                help_text="Send an email when another user comments on your trips.",
                verbose_name="Comment emails",
            ),
        ),
    ]
