# Generated by Django 4.2.3 on 2023-07-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0031_cavinguser_has_mod_perms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cavinguser",
            name="show_cavers_on_trip_list",
            field=models.BooleanField(
                default=False,
                help_text="Enabling this option will display a list of cavers beneath each trip on your profile trip list.",
                verbose_name="Show cavers on trip list",
            ),
        ),
    ]
