# Generated by Django 4.2.3 on 2023-07-25 13:53

from django.db import migrations, models


def set_verified_email_flag(apps, schema_editor):
    """Set the has_verified_email flag to True for any user where is_active is True."""
    cavinguser = apps.get_model("users", "CavingUser")
    cavinguser.objects.filter(is_active=True).update(has_verified_email=True)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0032_alter_cavinguser_show_cavers_on_trip_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="cavinguser",
            name="has_verified_email",
            field=models.BooleanField(
                default=False,
                help_text="Has the user verified their email address?",
                verbose_name="Email verified",
            ),
        ),
        migrations.RunPython(set_verified_email_flag, reverse_code=migrations.RunPython.noop),
    ]
