# Generated by Django 4.2.6 on 2023-10-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0033_cavinguser_has_verified_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cavinguser",
            name="allow_comments",
            field=models.BooleanField(
                default=True,
                help_text="If enabled, other users will be able to comment on your trips. Disabling this setting will not delete any existing comments, but will hide them until it is re-enabled.",
                verbose_name="Allow comments on your trips",
            ),
        ),
    ]
