# Generated by Django 4.2.6 on 2023-10-25 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0031_delete_tripreport"),
        ("users", "0034_alter_cavinguser_allow_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="trip",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="logger.trip"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("A", "Free text"), ("B", "Trip like"), ("C", "Trip comment")],
                default="A",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="notification",
            name="url",
            field=models.URLField(blank=True, max_length=255, verbose_name="URL"),
        ),
    ]
