# Generated by Django 4.2.7 on 2023-11-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_cavinguser_email_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
