# Generated by Django 4.2.6 on 2023-11-09 09:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0036_alter_cavinguser_email_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cavinguser",
            name="page_title",
        ),
    ]
