# Generated by Django 4.2.7 on 2023-12-10 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0038_remove_cavinguser_page_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="cavinguser",
            name="discord",
            field=models.CharField(
                blank=True,
                help_text="Your Discord username.",
                max_length=32,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
        migrations.AddField(
            model_name="cavinguser",
            name="facebook",
            field=models.CharField(
                blank=True,
                help_text="Your Facebook username.",
                max_length=50,
                validators=[django.core.validators.MinLengthValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="cavinguser",
            name="instagram",
            field=models.CharField(blank=True, help_text="Your Instagram username.", max_length=30),
        ),
        migrations.AddField(
            model_name="cavinguser",
            name="website",
            field=models.URLField(blank=True, help_text="A link to your personal website."),
        ),
        migrations.AddField(
            model_name="cavinguser",
            name="x_username",
            field=models.CharField(blank=True, help_text="Your X username.", max_length=15),
        ),
    ]
