# Generated by Django 4.2.7 on 2023-12-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0039_cavinguser_discord_cavinguser_facebook_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cavinguser",
            name="x_username",
            field=models.CharField(
                blank=True,
                help_text="Your X username.",
                max_length=15,
                verbose_name="X/Twitter",
            ),
        ),
    ]
