# Generated by Django 4.2 on 2023-12-17 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0040_alter_cavinguser_x_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cavinguser",
            name="discord",
        ),
        migrations.AlterField(
            model_name="cavinguser",
            name="facebook",
            field=models.CharField(
                blank=True,
                help_text="Your Facebook username.",
                max_length=50,
                validators=[
                    django.core.validators.MinLengthValidator(5),
                    django.core.validators.RegexValidator(
                        "^[^\\s]*$", "This field cannot contain whitespace."
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cavinguser",
            name="instagram",
            field=models.CharField(
                blank=True,
                help_text="Your Instagram username.",
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[^\\s]*$", "This field cannot contain whitespace."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cavinguser",
            name="x_username",
            field=models.CharField(
                blank=True,
                help_text="Your X username.",
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[^\\s]*$", "This field cannot contain whitespace."
                    )
                ],
                verbose_name="X/Twitter",
            ),
        ),
    ]
