# Generated by Django 4.2 on 2023-12-17 19:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0041_remove_cavinguser_discord_alter_cavinguser_facebook_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cavinguser",
            name="private_notes",
        ),
    ]
