FROM postgres:15.3

# postgis/postgis docker images do not provide an arm64 build which leads
# to very poor performance on Apple Silicon. This is a workaround to
# use the official postgres arm64 build and then install postgis
# on top.
RUN apt update
RUN apt install postgis -y

# Load blank database with an admin user only
COPY ./config/docker/dev_db_data.sql /docker-entrypoint-initdb.d/
