# Generated by Django 2.0.6 on 2018-06-26 10:57

import distancefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                (
                    "mm_field",
                    distancefield.fields.DistanceField(
                        decimal_places=6,
                        max_digits=14,
                        unit="mm",
                        unit_field="mm_field_units",
                    ),
                ),
                (
                    "inch_field",
                    distancefield.fields.DistanceField(
                        decimal_places=6,
                        max_digits=14,
                        unit="inch",
                        unit_field="inch_field_units",
                    ),
                ),
                (
                    "mtr_field",
                    distancefield.fields.DistanceField(
                        decimal_places=6,
                        max_digits=14,
                        unit="m",
                        unit_field="mtr_field_units",
                    ),
                ),
                (
                    "mm_field_units",
                    distancefield.fields.DistanceUnitField(
                        blank=True, max_length=29, null=True
                    ),
                ),
                (
                    "inch_field_units",
                    distancefield.fields.DistanceUnitField(
                        blank=True, max_length=29, null=True
                    ),
                ),
                (
                    "mtr_field_units",
                    distancefield.fields.DistanceUnitField(
                        blank=True, max_length=29, null=True
                    ),
                ),
            ],
        ),
    ]
