# Generated by Django 4.2.2 on 2023-06-23 15:49

import distancefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("distancefield", "0002_testmodel_no_unit_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistanceFieldTestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                (
                    "mm_field",
                    distancefield.fields.DistanceField(
                        decimal_places=6,
                        max_digits=14,
                        unit="mm",
                        unit_field="mm_field_units",
                    ),
                ),
                (
                    "inch_field",
                    distancefield.fields.DistanceField(
                        decimal_places=6,
                        max_digits=14,
                        unit="inch",
                        unit_field="inch_field_units",
                    ),
                ),
                (
                    "mtr_field",
                    distancefield.fields.DistanceField(
                        decimal_places=6,
                        max_digits=14,
                        unit="m",
                        unit_field="mtr_field_units",
                    ),
                ),
                (
                    "no_unit_field",
                    distancefield.fields.DistanceField(
                        decimal_places=6, default="10in", max_digits=14, unit="inch"
                    ),
                ),
                (
                    "mm_field_units",
                    distancefield.fields.DistanceUnitField(
                        blank=True, editable=False, max_length=29, null=True
                    ),
                ),
                (
                    "inch_field_units",
                    distancefield.fields.DistanceUnitField(
                        blank=True, editable=False, max_length=29, null=True
                    ),
                ),
                (
                    "mtr_field_units",
                    distancefield.fields.DistanceUnitField(
                        blank=True, editable=False, max_length=29, null=True
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="TestModel",
        ),
    ]
