# Generated by Django 4.1.7 on 2023-03-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="cave_url",
            field=models.URLField(
                blank=True,
                help_text="A website, such as a Wikipedia page, giving more information on this cave.",
                verbose_name="cave website",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="report_url",
            field=models.URLField(
                blank=True,
                help_text="The URL of an externally hosted trip report, such as on an expedition website or a personal blog.",
                verbose_name="trip report",
            ),
        ),
    ]
