# Generated by Django 4.2.1 on 2023-05-24 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0001_squash_all_logger"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
