# Generated by Django 4.1.7 on 2023-03-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="privacy",
            field=models.CharField(
                choices=[
                    ("Inherit", "Inherit"),
                    ("Public", "Public"),
                    ("Private", "Private"),
                ],
                default="Inherit",
                help_text="If set to 'inherit', the trip will have the same privacy settings as your user profile.",
                max_length=10,
                verbose_name="Privacy settings",
            ),
        ),
    ]
