# Generated by Django 4.1.7 on 2023-03-24 14:02

import distance.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="aid_dist_units",
            field=distance.fields.DistanceUnitField(
                blank=True, editable=False, max_length=29, null=True
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="horizontal_dist_units",
            field=distance.fields.DistanceUnitField(
                blank=True, editable=False, max_length=29, null=True
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="surveyed_dist_units",
            field=distance.fields.DistanceUnitField(
                blank=True, editable=False, max_length=29, null=True
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="vert_dist_down_units",
            field=distance.fields.DistanceUnitField(
                blank=True, editable=False, max_length=29, null=True
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="vert_dist_up_units",
            field=distance.fields.DistanceUnitField(
                blank=True, editable=False, max_length=29, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="aid_dist",
            field=distance.fields.DistanceField(
                blank=True,
                decimal_places=6,
                help_text="Distance covered by aid climbing.",
                max_digits=14,
                null=True,
                unit="m",
                unit_field="aid_dist_units",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="aid climbing distance",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="horizontal_dist",
            field=distance.fields.DistanceField(
                blank=True,
                decimal_places=6,
                help_text="Horizontal distance covered.",
                max_digits=14,
                null=True,
                unit="m",
                unit_field="horizontal_dist_units",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="horizontal distance",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="surveyed_dist",
            field=distance.fields.DistanceField(
                blank=True,
                decimal_places=6,
                help_text="Distance surveyed.",
                max_digits=14,
                null=True,
                unit="m",
                unit_field="surveyed_dist_units",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="surveyed distance",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="vert_dist_down",
            field=distance.fields.DistanceField(
                blank=True,
                decimal_places=6,
                help_text="Distance descended on rope.",
                max_digits=14,
                null=True,
                unit="m",
                unit_field="vert_dist_down_units",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="rope descent distance",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="vert_dist_up",
            field=distance.fields.DistanceField(
                blank=True,
                decimal_places=6,
                help_text="Distance ascended on rope.",
                max_digits=14,
                null=True,
                unit="m",
                unit_field="vert_dist_up_units",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="rope ascent distance",
            ),
        ),
    ]
