# Generated by Django 4.2.1 on 2023-05-27 10:44

from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0002_delete_comment"),
    ]

    operations = [
        UnaccentExtension(),
        TrigramExtension(),
    ]
