# Generated by Django 4.1.7 on 2023-03-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0003_alter_trip_aid_dist_alter_trip_horizontal_dist_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="type",
            field=models.CharField(
                choices=[
                    ("Sport", "Sport"),
                    ("Digging", "Digging"),
                    ("Survey", "Survey"),
                    ("Exploration", "Exploration"),
                    ("Aid climbing", "Aid climbing"),
                    ("Photography", "Photography"),
                    ("Training", "Training"),
                    ("Rescue", "Rescue"),
                    ("Science", "Science"),
                    ("Surface", "Surface"),
                    ("Other", "Other"),
                ],
                default="Sport",
                max_length=15,
            ),
        ),
    ]
