# Generated by Django 4.2.1 on 2023-06-03 21:46
import humanize
from django.db import migrations


def update_all_duration_str(apps, schema_editor):  # pragma: no cover
    Trip = apps.get_model("logger", "Trip")
    for trip in Trip.objects.all():
        td = None
        if trip.end:
            td = trip.end - trip.start

        if td:
            trip.duration_str = humanize.precisedelta(
                td, minimum_unit="minutes", suppress=["days", "months", "years"]
            )
        else:
            trip.duration_str = None
        trip.save()


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0003_install_postgres_unaccent_and_trigram"),
    ]

    operations = [
        migrations.RunPython(
            update_all_duration_str, reverse_code=migrations.RunPython.noop
        )
    ]
