# Generated by Django 4.1.7 on 2023-03-27 19:35

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logger", "0004_alter_trip_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="TripReport",
            fields=[
                (
                    "trip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="report",
                        serialize=False,
                        to="logger.trip",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "pub_date",
                    models.DateField(
                        help_text="The date which will be shown on the report.",
                        verbose_name="date published",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="A unique identifier for the URL of the report. No spaces or special characters allowed.",
                        max_length=100,
                    ),
                ),
                ("content", tinymce.models.HTMLField()),
                (
                    "added",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="report added on"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="report last updated"
                    ),
                ),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            (
                                "Anyone, if they can view the trip",
                                "Anyone, if they can view the trip",
                            ),
                            (
                                "Anyone, even if the trip is private",
                                "Anyone, even if the trip is private",
                            ),
                            ("Only my friends", "Only my friends"),
                            ("Only me", "Only me"),
                        ],
                        default="Anyone, if they can view the trip",
                        max_length=40,
                        verbose_name="Who can view",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "slug")},
            },
        ),
    ]
