# Generated by Django 4.2.1 on 2023-06-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0004_update_all_duration_str"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="cave_entrance",
            field=models.CharField(
                blank=True,
                help_text="The location at which you entered the cave. Can be left blank.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="cave_exit",
            field=models.CharField(
                blank=True,
                help_text="The location at which you exited the cave. Can be left blank.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="cave_name",
            field=models.CharField(
                help_text="The name of the cave or cave system entered.", max_length=100
            ),
        ),
    ]
