# Generated by Django 4.2.1 on 2023-06-04 01:17

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0005_trip_cave_entrance_trip_cave_exit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="A unique identifier for this trip.",
                null=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="cave_country",
            field=models.CharField(
                blank=True,
                help_text="The country in which the cave is located.",
                max_length=100,
                verbose_name="country",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="cave_entrance",
            field=models.CharField(
                blank=True,
                help_text="The location at which you entered the cave.",
                max_length=100,
                verbose_name="entrance",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="cave_exit",
            field=models.CharField(
                blank=True,
                help_text="The location at which you exited the cave.",
                max_length=100,
                verbose_name="exit",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="cave_region",
            field=models.CharField(
                blank=True,
                help_text="The state or region in which the cave is located.",
                max_length=100,
                verbose_name="region",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="cave_url",
            field=models.URLField(
                blank=True,
                help_text="A website, such as a Wikipedia page, giving more information on this cave.",
                verbose_name="website",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="cavers",
            field=models.CharField(
                blank=True,
                help_text="A comma-separated list of cavers that were on this trip. Avoid adding yourself to this list.",
                max_length=250,
            ),
        ),
    ]
