# Generated by Django 4.1.7 on 2023-03-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0006_remove_trip_report_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="cavers",
            field=models.CharField(
                blank=True,
                help_text="A list of cavers that were on this trip.",
                max_length=250,
            ),
        ),
    ]
