# Generated by Django 4.1.7 on 2023-03-30 14:39

import distance.fields
from django.db import migrations
import logger.validators


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0008_alter_trip_privacy_alter_tripreport_privacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="resurveyed_dist",
            field=distance.fields.DistanceField(
                blank=True,
                decimal_places=6,
                help_text="Distance resurveyed.",
                max_digits=14,
                null=True,
                unit="m",
                unit_field="resurveyed_dist_units",
                validators=[
                    logger.validators.above_zero_dist_validator,
                    logger.validators.horizontal_dist_validator,
                ],
                verbose_name="resurveyed distance",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="resurveyed_dist_units",
            field=distance.fields.DistanceUnitField(
                blank=True, editable=False, max_length=29, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="surveyed_dist",
            field=distance.fields.DistanceField(
                blank=True,
                decimal_places=6,
                help_text="New passage surveyed.",
                max_digits=14,
                null=True,
                unit="m",
                unit_field="surveyed_dist_units",
                validators=[
                    logger.validators.above_zero_dist_validator,
                    logger.validators.horizontal_dist_validator,
                ],
                verbose_name="surveyed distance",
            ),
        ),
    ]
