# Generated by Django 4.2.2 on 2023-06-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0009_tripphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="custom_field_1",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="trip",
            name="custom_field_2",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="trip",
            name="custom_field_3",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="trip",
            name="custom_field_4",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="trip",
            name="custom_field_5",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
