# Generated by Django 4.2.2 on 2023-06-10 18:56

from django.db import migrations, models

import logger.models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0010_trip_custom_field_1_trip_custom_field_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripphoto",
            name="original_file_name",
            field=models.CharField(default="file", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tripphoto",
            name="uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tripphoto",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage="photos",
                upload_to=logger.models.trip_photo_upload_path,
            ),
        ),
    ]
