# Generated by Django 4.2.2 on 2023-06-10 19:42

from django.db import migrations, models

import logger.models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0011_tripphoto_original_file_name_tripphoto_uploaded_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tripphoto",
            name="photo",
            field=models.ImageField(
                blank=True,
                max_length=150,
                null=True,
                storage="photos",
                upload_to=logger.models.trip_photo_upload_path,
            ),
        ),
    ]
