# Generated by Django 4.1.7 on 2023-04-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0012_set_all_duration_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="cavers",
            field=models.CharField(
                blank=True,
                help_text="A comma-separated list of cavers that were on this trip.",
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="clubs",
            field=models.CharField(
                blank=True,
                help_text="A comma-separated list of any caving clubs associated with this trip.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="expedition",
            field=models.CharField(
                blank=True,
                help_text="A comma-separated list of any expeditions associated with this trip.",
                max_length=100,
            ),
        ),
    ]
