# Generated by Django 4.2.2 on 2023-06-10 20:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logger", "0012_alter_tripphoto_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tripphoto",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="logger.trip",
            ),
        ),
        migrations.AlterField(
            model_name="tripphoto",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="tripphoto",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name="UUID"),
        ),
    ]
