# Generated by Django 4.2.2 on 2023-06-10 22:30

import storages.backends.s3boto3
from django.db import migrations, models

import logger.models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0013_alter_tripphoto_trip_alter_tripphoto_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tripphoto",
            name="photo",
            field=models.ImageField(
                blank=True,
                max_length=150,
                null=True,
                storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name="caves.app"),
                upload_to=logger.models.trip_photo_upload_path,
            ),
        ),
    ]
