# Generated by Django 4.2.2 on 2023-06-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0014_alter_tripphoto_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tripphoto",
            name="original_file_name",
        ),
        migrations.RemoveField(
            model_name="tripphoto",
            name="uploaded_at",
        ),
        migrations.AddField(
            model_name="tripphoto",
            name="is_valid",
            field=models.BooleanField(default=False),
        ),
    ]
