# Generated by Django 4.1.7 on 2023-04-22 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logger", "0014_alter_tripreport_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_trips", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tripreport",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_reports", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
