# Generated by Django 4.2.2 on 2023-06-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0016_trip_private_photos"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripphoto",
            name="taken",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
