# Generated by Django 4.2 on 2023-04-23 22:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0017_rename_comment_comment_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-added"]},
        ),
    ]
