# Generated by Django 4.2.2 on 2023-06-17 07:32

import logger.models.tripphoto
import storages.backends.s3boto3
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0017_tripphoto_taken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tripphoto",
            name="photo",
            field=models.ImageField(
                blank=True,
                max_length=150,
                null=True,
                storage=storages.backends.s3boto3.S3Boto3Storage(
                    location="p", bucket_name="caves.app"
                ),
                upload_to=logger.models.tripphoto.trip_photo_upload_path,
            ),
        ),
    ]
