# Generated by Django 4.2.3 on 2023-07-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0020_alter_tripphoto_trip_alter_tripphoto_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripphoto",
            name="filesize",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
