# Generated by Django 4.2.3 on 2023-07-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0021_tripphoto_filesize"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tripphoto",
            name="filesize",
            field=models.IntegerField(default=0),
        ),
    ]
