# Generated by Django 4.2.3 on 2023-07-27 10:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0022_alter_tripphoto_filesize"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="cave_coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                default=None,
                geography=True,
                help_text="The coordinates of the cave in WGS84 format.",
                null=True,
                srid=4326,
                verbose_name="coordinates",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="cave_location",
            field=models.CharField(
                blank=True,
                help_text="The location of the cave in the form of a decimal latitude and longitude separated by a comma, or the name of a nearby street, town or postcode.",
                max_length=100,
                verbose_name="location",
            ),
        ),
    ]
