# Generated by Django 4.2.3 on 2023-07-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0023_trip_cave_coordinates_trip_cave_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="cave_location",
            field=models.CharField(
                blank=True,
                help_text="Enter a decimal latitude and longitude, address, or place name.",
                max_length=100,
                verbose_name="location",
            ),
        ),
    ]
