# Generated by Django 4.2.3 on 2023-07-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0025_remove_trip_cave_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="cave_location",
            field=models.CharField(
                blank=True,
                help_text="Enter a decimal latitude and longitude, address, or place name. Cave locations are not visible to other users.",
                max_length=100,
                verbose_name="location",
            ),
        ),
    ]
