# Generated by Django 4.2.6 on 2023-10-06 04:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0026_alter_trip_cave_location"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tripreport",
            name="unique_slug_per_user",
        ),
        migrations.RemoveField(
            model_name="tripreport",
            name="pub_date",
        ),
        migrations.RemoveField(
            model_name="tripreport",
            name="slug",
        ),
    ]
