# Generated by Django 4.2.6 on 2023-10-20 09:29

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0027_remove_tripreport_unique_slug_per_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="trip_report",
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
