# Generated by Django 4.2.3 on 2023-07-29 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("caves", "0001_initial"),
        ("logger", "0027_trip_entrance_trip_system"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="entrance",
            new_name="entered_by",
        ),
        migrations.AddField(
            model_name="trip",
            name="exited_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exits",
                to="caves.caveentrance",
            ),
        ),
    ]
