# Generated by Django 4.2.6 on 2023-10-20 09:34

from django.db import migrations


def migrate_trip_report_content_to_trips(apps, schema_editor):
    trip_report = apps.get_model("logger", "TripReport")
    trip = apps.get_model("logger", "Trip")

    for report in trip_report.objects.all():
        trip.objects.filter(pk=report.trip.pk).update(trip_report=report.content)
        if report.privacy == "Friends":
            trip.objects.filter(pk=report.trip.pk).update(privacy="Friends")
        elif report.privacy == "Private":
            trip.objects.filter(pk=report.trip.pk).update(privacy="Private")


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0028_trip_trip_report"),
    ]

    operations = [
        migrations.RunPython(
            migrate_trip_report_content_to_trips, reverse_code=migrations.RunPython.noop
        ),
    ]
