# Generated by Django 4.2.6 on 2023-10-20 09:44

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0029_migrate_trip_report_content_to_trips"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Trip notes should contain brief details of the trip, and may be private depending on your account settings. For full trip reports, use the trip report field below.",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="trip_report",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Trip reports are full, article style reports of a trip and will be visible to anyone who can view the trip.",
            ),
        ),
    ]
