# Generated by Django 4.2.6 on 2023-10-20 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0030_alter_trip_notes_alter_trip_trip_report"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TripReport",
        ),
    ]
