# Generated by Django 4.2.6 on 2023-11-01 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logger", "0037_rename_caver_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="caver",
            name="linked_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_cavers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
