# Generated by Django 4.2.7 on 2023-11-17 10:49

from django.db import migrations, models
import logger.models.tripphoto
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0038_caver_linked_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripphoto',
            name='photo',
            field=models.ImageField(blank=True, max_length=150, null=True, storage=storages.backends.s3.S3Storage(location='p'), upload_to=logger.models.tripphoto.trip_photo_upload_path),
        ),
    ]
