# Generated by Django 4.2.7 on 2023-12-10 19:51

import django.db.models.deletion
import logger.models.tripphoto
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0038_caver_linked_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="featured_photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trips_featured",
                to="logger.tripphoto",
            ),
        ),
    ]
