# Generated by Django 4.2.7 on 2023-12-11 18:25

import storages.backends.s3
from django.db import migrations, models

import logger.models.tripphoto


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0039_add_trip_featured_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripphoto",
            name="photo_type",
            field=models.CharField(
                choices=[("FT", "Featured"), ("DE", "Default")],
                default="DE",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="tripphoto",
            name="photo",
            field=models.ImageField(
                blank=True,
                max_length=150,
                null=True,
                storage=storages.backends.s3.S3Storage(location="p"),
                upload_to=logger.models.tripphoto.trip_photo_upload_path,
            ),
        ),
    ]
