# Generated by Django 4.2.7 on 2023-12-12 21:37

from django.db import migrations, models


def copy_trip_report_to_trip_report_new(apps, schema_editor):
    Trip = apps.get_model("logger", "Trip")
    for trip in Trip.objects.all():
        trip.trip_report_new = trip.trip_report
        trip.save()


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0040_tripphoto_photo_type_alter_tripphoto_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="trip_report_new",
            field=models.TextField(
                blank=True,
                help_text="Trip reports are full, article style reports of a trip and will be visible to anyone who can view the trip.",
            ),
        ),
        migrations.RunPython(copy_trip_report_to_trip_report_new),
    ]
