# Generated by Django 4.2.7 on 2023-12-12 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0041_change_trip_report_field_to_textfield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="trip_report",
        ),
        migrations.RenameField(
            model_name="trip",
            old_name="trip_report_new",
            new_name="trip_report",
        ),
    ]
