# Generated by Django 4.2 on 2023-12-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0042_swap_trip_report_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="trip_report",
            field=models.TextField(
                blank=True,
                help_text="Trip reports are full, article style reports of a trip and will be visible to anyone who can view the trip. Some <a href='https://www.markdownguide.org/basic-syntax/'>Markdown</a> is supported.",
            ),
        ),
    ]
