# Generated by Django 4.2 on 2023-12-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0043_alter_trip_trip_report"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="trip_report",
            new_name="public_notes",
        ),
    ]
