# Generated by Django 4.2 on 2023-12-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0044_remove_trip_trip_report_trip_public_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
