# Generated by Django 4.2 on 2023-04-25 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("core", "0001_initial"),
        ("core", "0002_alter_news_options_news_author"),
        ("core", "0003_news_is_published_alter_news_posted_at"),
        ("core", "0004_alter_news_is_published"),
        ("core", "0005_news_added_news_updated"),
        ("core", "0006_alter_news_added_alter_news_updated"),
        ("core", "0007_faq"),
        ("core", "0008_alter_faq_options"),
        ("core", "0009_alter_faq_answer_alter_news_content"),
        ("core", "0010_alter_news_posted_at"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=100)),
                ("answer", models.TextField(help_text="Markdown is supported.")),
                (
                    "added",
                    models.DateTimeField(auto_now_add=True, verbose_name="added on"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="last updated"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("posted_at", models.DateTimeField()),
                ("content", models.TextField(help_text="Markdown is supported.")),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        help_text="News items will not appear on the site unless this box is checked.",
                        verbose_name="Publish",
                    ),
                ),
                (
                    "added",
                    models.DateTimeField(auto_now_add=True, verbose_name="added on"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="last updated"),
                ),
            ],
            options={
                "verbose_name_plural": "news",
            },
        ),
    ]
