# Generated by Django 4.2.1 on 2023-06-04 17:08

from django.db import migrations, models
from django.utils.text import slugify


def assign_slugs_to_news(apps, schema_editor):  # pragma: no cover
    News = apps.get_model("core", "News")
    for news in News.objects.all():
        news.slug = slugify(news.title)
        news.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_news_slug"),
    ]

    operations = [
        migrations.RunPython(
            assign_slugs_to_news,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(
                default="djangodbmodelsfieldscharfield", max_length=100, unique=True
            ),
        ),
    ]
