# Generated by Django 4.1.7 on 2023-04-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_news_is_published_alter_news_posted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="is_published",
            field=models.BooleanField(
                help_text="News items will not appear on the site unless this box is checked.",
                verbose_name="Publish",
            ),
        ),
    ]
