# Generated by Django 4.2.1 on 2023-06-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_news_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
