# Generated by Django 4.1.7 on 2023-04-03 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_news_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="added",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="trip added on",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="news",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="trip last updated"),
        ),
    ]
