# Generated by Django 4.1.7 on 2023-04-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_news_added_news_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="added",
            field=models.DateTimeField(auto_now_add=True, verbose_name="added on"),
        ),
        migrations.AlterField(
            model_name="news",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="last updated"),
        ),
    ]
