# Generated by Django 4.1.7 on 2023-04-03 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_faq"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faq",
            options={"verbose_name": "FAQ"},
        ),
    ]
