# Generated by Django 4.1.7 on 2023-04-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_faq_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.TextField(help_text="Markdown is supported."),
        ),
        migrations.AlterField(
            model_name="news",
            name="content",
            field=models.TextField(help_text="Markdown is supported."),
        ),
    ]
