# Generated by Django 4.2 on 2023-04-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_faq_answer_alter_news_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="posted_at",
            field=models.DateTimeField(),
        ),
    ]
