# Generated by Django 4.1.7 on 2023-04-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0002_friendrequest"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="friendrequest",
            constraint=models.UniqueConstraint(
                fields=("user_from", "user_to"), name="unique_friend_request"
            ),
        ),
    ]
