# syntax=docker/dockerfile:1

################
### Builder ####
################
FROM python:3.11.4-alpine as builder

# Set working directory
WORKDIR /usr/src/caves

# Environment setup
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install psycopg2 dependencies
RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev libmagic

# Python packages
RUN pip install --upgrade pip
COPY ./config/requirements/production.txt requirements.txt
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/caves/wheels -r requirements.txt

##################
### Production ###
##################
FROM python:3.11.4-alpine

# Install psycopg2 depencencies
RUN apk update && apk add libpq

# Copy wheels
COPY --from=builder /usr/src/caves/wheels /opt/caves/wheels
RUN pip install --no-cache /opt/caves/wheels/*

# Create directories
RUN mkdir -p /opt/caves /opt/caves/config

# Copy entrypoint
COPY ./config/docker/production/entrypoint.prod.sh /opt/caves/config
RUN chmod +x /opt/caves/config/entrypoint.prod.sh

# Set Python path for config directory
RUN touch /opt/caves/config/__init__.py
ENV PYTHONPATH "/opt/caves/"

# Set up user
RUN addgroup --g 1001 caves
RUN adduser -u 1001 -G caves -h /opt/caves -D caves
RUN chown caves:caves -R /opt/caves
USER caves
WORKDIR /opt/caves/app

# Set base dir for Django contrib
ENV BASE_DIR "/opt/caves/app"

# Run entrypoint.sh.
ENTRYPOINT ["/opt/caves/config/entrypoint.prod.sh"]
