name: Deploy

concurrency: deploy

on:
  workflow_run:
    workflows:
      - Tests
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    name: Deploy caves.app
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy caves.app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}
          script: ${{ secrets.DEPLOY_SSH_SCRIPT }}
