name: Run Django Tests

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      DATABASE: postgres
      SQL_ENGINE: django.db.backends.postgresql
      SQL_USER: postgres
      SQL_PASSWORD: postgres
      SQL_DATABASE: postgres
      SQL_HOST: localhost
      SQL_PORT: 5432
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Set up Python 3.11.3
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3
      - name: Upgrade pip
        run: |
          pip install --upgrade pip wheel
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Django tests
        working-directory: ./app
        run: |
          coverage run --source=. ./manage.py test -v 2 --timing --parallel auto --noinput
          coverage xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
    services:
      postgres:
        image: postgres:15.2
        env:
          POSTGRES_USER: ${{ env.SQL_USER }}
          POSTGRES_PASSWORD: ${{ env.SQL_PASSWORD }}
          POSTGRES_DB: ${{ env.DATABASE }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
